CREATE TABLE IF NOT EXISTS metrics (
  id SERIAL PRIMARY KEY,
  resource_name VARCHAR(255) NOT NULL,
  cpu_usage NUMERIC(5,2) NOT NULL,
  memory_usage NUMERIC(5,2) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
