name: App DockerHub Build & Push

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'docker/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - 'docker/**'
  workflow_dispatch:

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-dockerhub:
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_REPO: multi-cloud-cost-and-service-status-dashboard-repo
      VERSION: v${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Detect changes
        id: changes
        run: |
          echo "Detecting changed files..."
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual trigger detected — all steps will run."
            echo "backend=manual" >> $GITHUB_OUTPUT
            echo "worker=manual" >> $GITHUB_OUTPUT
            echo "frontend=manual" >> $GITHUB_OUTPUT
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
            echo "Changed files:"
            echo "$CHANGED_FILES"

            CHANGED_BACKEND=$(echo "$CHANGED_FILES" | grep -E '^app/backend/|^docker/backend/' || true)
            CHANGED_WORKER=$(echo "$CHANGED_FILES" | grep -E '^app/worker/|^docker/worker/' || true)
            CHANGED_FRONTEND=$(echo "$CHANGED_FILES" | grep -E '^app/frontend/|^docker/frontend/' || true)

            [ -n "$CHANGED_BACKEND" ] && echo "backend=$CHANGED_BACKEND" >> $GITHUB_OUTPUT || echo "backend=" >> $GITHUB_OUTPUT
            [ -n "$CHANGED_WORKER" ] && echo "worker=$CHANGED_WORKER" >> $GITHUB_OUTPUT || echo "worker=" >> $GITHUB_OUTPUT
            [ -n "$CHANGED_FRONTEND" ] && echo "frontend=$CHANGED_FRONTEND" >> $GITHUB_OUTPUT || echo "frontend=" >> $GITHUB_OUTPUT
          fi

      - name: Build & Push Backend
        if: steps.changes.outputs.backend != ''
        run: |
          echo "=== BACKEND STEP RUNNING ==="
          if [ "${{ steps.changes.outputs.backend }}" == "manual" ]; then
            echo "Reason: Manual trigger"
          else
            echo "Reason: Files changed in backend:"
            echo "${{ steps.changes.outputs.backend }}"
          fi
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-latest -t $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-${VERSION} -f docker/backend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-${VERSION}

      - name: Skip Backend
        if: steps.changes.outputs.backend == ''
        run: echo "=== BACKEND STEP SKIPPED — No changes ==="

      - name: Build & Push Worker
        if: steps.changes.outputs.worker != ''
        run: |
          echo "=== WORKER STEP RUNNING ==="
          if [ "${{ steps.changes.outputs.worker }}" == "manual" ]; then
            echo "Reason: Manual trigger"
          else
            echo "Reason: Files changed in worker:"
            echo "${{ steps.changes.outputs.worker }}"
          fi
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-latest -t $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-${VERSION} -f docker/worker/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-${VERSION}

      - name: Skip Worker
        if: steps.changes.outputs.worker == ''
        run: echo "=== WORKER STEP SKIPPED — No changes ==="

      - name: Build & Push Frontend
        if: steps.changes.outputs.frontend != ''
        run: |
          echo "=== FRONTEND STEP RUNNING ==="
          if [ "${{ steps.changes.outputs.frontend }}" == "manual" ]; then
            echo "Reason: Manual trigger"
          else
            echo "Reason: Files changed in frontend:"
            echo "${{ steps.changes.outputs.frontend }}"
          fi
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-latest -t $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-${VERSION} -f docker/frontend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-${VERSION}

      - name: Skip Frontend
        if: steps.changes.outputs.frontend == ''
        run: echo "=== FRONTEND STEP SKIPPED — No changes ==="
