name: App DockerHub Build & Push

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'docker/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - 'docker/**'
  workflow_dispatch:

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-dockerhub:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.actor == 'Mahesh-Kotakonda')
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_REPO: multi-cloud-cost-and-service-status-dashboard-repo
      VERSION: v${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # ===== BACKEND =====
      - name: Build & Push Backend
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-latest \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-${VERSION} \
            -f docker/backend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-${VERSION}

      # ===== WORKER =====
      - name: Build & Push Worker
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-latest \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-${VERSION} \
            -f docker/worker/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-${VERSION}

      # ===== FRONTEND =====
      - name: Build & Push Frontend
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-latest \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-${VERSION} \
            -f docker/frontend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-${VERSION}
