name: App DockerHub Build & Push

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'docker/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - 'docker/**'
  workflow_dispatch:

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-dockerhub:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.actor == 'Mahesh-Kotakonda')
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_REPO: multi-cloud-cost-and-service-status-dashboard-repo
      VERSION: v${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # ===== BACKEND =====
      - name: Build & Push Backend
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-latest \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-${VERSION} \
            -f docker/backend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:backend-${VERSION}

      # ===== WORKER =====
      - name: Build & Push Worker
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-latest \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-${VERSION} \
            -f docker/worker/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:worker-${VERSION}

      # ===== FRONTEND =====
      - name: Build & Push Frontend
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-latest \
            -t $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-${VERSION} \
            -f docker/frontend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:frontend-${VERSION}

  deploy-worker:
    needs: build-and-push-dockerhub
    runs-on: self-hosted
    env:
      INFRA_JSON_PATH: ./infra.json
      S3_JSON_PATH: s3://multi-cloud-cost-and-service-status-dashboard/infra/multi-cloud-dashboard-outputs.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Terraform output JSON
        run: |
          aws s3 cp $S3_JSON_PATH $INFRA_JSON_PATH || exit 1

      - name: Verify JSON file exists
        run: |
          if [ ! -f "$INFRA_JSON_PATH" ]; then
            echo "ERROR: Terraform infra.json not found. Contact infrastructure team."
            exit 1
          fi

      - name: Extract variables from JSON
        id: extract
        run: |
          DB_HOST=$(jq -r '.db.endpoint' $INFRA_JSON_PATH | cut -d: -f1)
          DB_NAME=$(jq -r '.db.name' $INFRA_JSON_PATH)
          AWS_REGION=$(echo "$DB_HOST" | awk -F. '{print $4}')
          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV
          echo "SSM_PARAM_NAME=myapp_database_credentials" >> $GITHUB_ENV

      - name: Run Worker container
        run: |
          docker run --rm \
            -e AWS_REGION=$AWS_REGION \
            -e DB_HOST=$DB_HOST \
            -e DB_NAME=$DB_NAME \
            -e SSM_PARAM_NAME=$SSM_PARAM_NAME \
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPO }}:worker-latest
