name: App DockerHub Build & Push

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'docker/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - 'docker/**'
  workflow_dispatch:

jobs:
  build-and-push-dockerhub:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.actor == 'Mahesh-Kotakonda')

    runs-on: self-hosted

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      BACKEND_REPO: multi-cloud-cost-and-service-status-dashboard-backend
      WORKER_REPO: multi-cloud-cost-and-service-status-dashboard-worker
      FRONTEND_REPO: multi-cloud-cost-and-service-status-dashboard-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # ===== BACKEND =====
      - name: Build & Push Backend
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/$BACKEND_REPO:latest \
            -f docker/backend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$BACKEND_REPO:latest

      # ===== WORKER =====
      - name: Build & Push Worker
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/$WORKER_REPO:latest \
            -f docker/worker/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$WORKER_REPO:latest

      # ===== FRONTEND =====
      - name: Build & Push Frontend
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/$FRONTEND_REPO:latest \
            -f docker/frontend/Dockerfile .
          docker push $DOCKERHUB_USERNAME/$FRONTEND_REPO:latest
