name: Infrastructure Destroy

on:
  workflow_dispatch:
  schedule:
    # - cron: '0 7 * * *'
    - cron: '30 14 * * *'

jobs:
  terraform-destroy:
    runs-on: self-hosted
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Destroy
        if: (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && github.actor == 'Mahesh-Kotakonda'
        working-directory: infra/terraform
        run: terraform destroy -auto-approve
        
        # Delete old Infrastructure output details JSON file from S3 before apply
      - name: Delete old outputs JSON from S3
        run: |
          aws s3 rm s3://multi-cloud-cost-and-service-status-dashboard/infra/multi-cloud-dashboard-outputs.json

