name: Infrastructure Creation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/terraform/**'
  push:
    branches:
      - main
    paths:
      - 'infra/terraform/**'
  workflow_dispatch:

jobs:
  # ---------------- SONARQUBE SCAN ---------------- #
  sonar-terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SonarScanner to PATH
        run: echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Verify SonarScanner CLI
        run: sonar-scanner --version

      - name: Run SonarQube Scan (Terraform)
        run: |
          sonar-scanner \
            -Dsonar.projectKey=terraform-infra \
            -Dsonar.projectName='Terraform Infrastructure' \
            -Dsonar.sources=infra/terraform \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Check SonarQube Quality Gate
        id: sonar-quality-gate
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


  # ---------------- TRIVY SCAN ---------------- #
  trivy-scan:
    runs-on: self-hosted
    needs: sonar-terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          if ! command -v trivy &> /dev/null; then
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
            sudo mv ./bin/trivy /usr/local/bin/
          fi
          trivy --version

      - name: Trivy FS Scan (Terraform Source)
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL infra/terraform

      - name: Trivy Config Scan (Terraform Config)
        run: trivy config --exit-code 1 --severity HIGH,CRITICAL infra/terraform

  # ---------------- TERRAFORM JOB ---------------- #
  terraform:
    runs-on: self-hosted
    needs: [trivy-scan]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: infra/terraform
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: infra/terraform
        run: terraform plan -no-color -out=tfplan

      - name: Delete old outputs JSON from S3
        run: |
          aws s3 rm s3://multi-cloud-cost-and-service-status-dashboard/infra/multi-cloud-dashboard-outputs.json

      - name: Terraform Apply
        id: apply
        if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')) && github.actor == 'Mahesh-Kotakonda'
        working-directory: infra/terraform
        run: terraform apply -auto-approve tfplan


