name: Infrastructure Creation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/terraform/**'
  push:
    branches:
      - main
    paths:
      - 'infra/terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Install Trivy for Terraform scanning
      - name: Install Trivy
        run: |
          if ! command -v trivy &> /dev/null; then
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
            sudo mv ./bin/trivy /usr/local/bin/
          fi
          trivy --version

      # Scan Terraform configuration
      - name: Trivy Terraform Config Scan
        run: |
          trivy config --exit-code 1 --severity HIGH,CRITICAL infra/terraform || true

      - name: Terraform Init
        id: init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: infra/terraform
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: infra/terraform
        run: terraform plan -no-color -out=tfplan

      - name: Delete old outputs JSON from S3
        run: |
          aws s3 rm s3://multi-cloud-cost-and-service-status-dashboard/infra/multi-cloud-dashboard-outputs.json

      - name: Terraform Apply
        id: apply
        if: (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')) && github.actor == 'Mahesh-Kotakonda'
        working-directory: infra/terraform
        run: terraform apply -auto-approve tfplan

