name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # All subsequent steps will use this working directory
      - name: Terraform Init
        id: init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: infra/terraform
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: infra/terraform
        run: terraform plan -no-color
